#!/bin/bash

# This script rebuilds the algorithmically-generated ftml files.

set -e

if [ ! -f wscript ]
then
	echo "Must be in the root of the project"
	exit 2
fi

# configure tests
tests="AllChars Proof Diac Matras Conjuncts"
urls='url(../references/JapaSansOriya-Regular.ttf)=refR url(../references/JapaSansOriya-Bold.ttf)=refB url(../results/JapaSansOriya-Regular.ttf)=R url(../results/JapaSansOriya-Bold.ttf)=B url(../references/NotoSansOriya-Regular.ttf)=notoSans url(../references/NotoSerifOriya-Regular.ttf)=notoSerif url(../references/BalooBhaina2-Regular.ttf)=baloo url(../references/AnekOdia-Regular.ttf)=ek  url(../references/Lohit-Odia.ttf)=lohit'
ufo='source/masters/JapaSansOriya-Thin.ufo'

# list all the fonts to test
fonts=''
for url in $urls
do
	fonts="$fonts -s '$url'"
done

echo "Rebuilding ftml files..."
for test in $tests
do
	base=${test,,}
	title="\"${test} auto\""
	ftml=tests/${base}.ftml
	log=tests/logs/${base}.log
	eval tools/psfgenftml.py -q -t "$title" --prevfont references/JapaSansOriya-Regular.ttf --norendercheck --scale 200 -i source/glyph_data.csv --xsl ../tools/ftml.xsl "$fonts" -l $log $ufo $ftml &
done
wait
echo "done."
