#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/masters/JapaSansOriya-Thin.ufo &
psfnormalize -p checkfix=fix source/masters/JapaSansOriya-Black.ufo &
psfnormalize -p checkfix=fix source/masters/JapaSansOriya-CondensedExtraThin.ufo &
psfnormalize -p checkfix=fix source/masters/JapaSansOriya-CondensedExtraBlack.ufo &
wait

# Apply glyph data to Thin UFO
psfsetpsnames -i source/glyph_data.csv source/masters/JapaSansOriya-Thin.ufo
psfsetglyphorder --header sort_final -i source/glyph_data.csv source/masters/JapaSansOriya-Thin.ufo

# Create WOFF metadata file
psfmakewoffmetadata -n JapaSansOriya -i org.sil.fonts -o source/JapaSansOriya-WOFF-metadata.xml source/masters/JapaSansOriya-Thin.ufo # --populateufowoff --force

# Copy metadata updates to all fonts
psfsyncmasters --complex source/JapaSansOriyaDesign.designspace

# Update FEA in UFO
psfmakefea -o source/masters/JapaSansOriya-Thin.ufo/features.fea -i source/opentype/master.feax source/masters/JapaSansOriya-Thin.ufo &
psfmakefea -o source/masters/JapaSansOriya-Black.ufo/features.fea -i source/opentype/master.feax source/masters/JapaSansOriya-Black.ufo &
psfmakefea -o source/masters/JapaSansOriya-CondensedExtraThin.ufo/features.fea -i source/opentype/master.feax source/masters/JapaSansOriya-CondensedExtraThin.ufo &
psfmakefea -o source/masters/JapaSansOriya-CondensedExtraBlack.ufo/features.fea -i source/opentype/master.feax source/masters/JapaSansOriya-CondensedExtraBlack.ufo &
wait
