#!/usr/bin/python3

Vowels = [
    0x0B05,  # ORIYA LETTER A
    0x0B06,  # ORIYA LETTER AA
    0x0B07,  # ORIYA LETTER I
    0x0B08,  # ORIYA LETTER II
    0x0B09,  # ORIYA LETTER U
    0x0B0A,  # ORIYA LETTER UU
    0x0B0B,  # ORIYA LETTER VOCALIC R
    0x0B0C,  # ORIYA LETTER VOCALIC L
    0x0B0F,  # ORIYA LETTER E
    0x0B10,  # ORIYA LETTER AI
    0x0B13,  # ORIYA LETTER O
    0x0B14,  # ORIYA LETTER AU
    0x0B60,  # ORIYA LETTER VOCALIC RR
    0x0B61,  # ORIYA LETTER VOCALIC LL
]

Matras = [
    0x0B3E,  # ORIYA VOWEL SIGN AA
    0x0B3F,  # ORIYA VOWEL SIGN I
    0x0B40,  # ORIYA VOWEL SIGN II
    0x0B41,  # ORIYA VOWEL SIGN U
    0x0B42,  # ORIYA VOWEL SIGN UU
    0x0B43,  # ORIYA VOWEL SIGN VOCALIC R
    0x0B44,  # ORIYA VOWEL SIGN VOCALIC RR
    0x0B47,  # ORIYA VOWEL SIGN E
    0x0B48,  # ORIYA VOWEL SIGN AI
    0x0B4B,  # ORIYA VOWEL SIGN O
    0x0B4C,  # ORIYA VOWEL SIGN AU
    0x0B62,  # ORIYA VOWEL SIGN VOCALIC L
    0x0B63,  # ORIYA VOWEL SIGN VOCALIC LL
    ]

Consonants = [
    0x0B15,  # ORIYA LETTER KA
    0x0B16,  # ORIYA LETTER KHA
    0x0B17,  # ORIYA LETTER GA
    0x0B18,  # ORIYA LETTER GHA
    0x0B19,  # ORIYA LETTER NGA
    0x0B1A,  # ORIYA LETTER CA
    0x0B1B,  # ORIYA LETTER CHA
    0x0B1C,  # ORIYA LETTER JA
    0x0B1D,  # ORIYA LETTER JHA
    0x0B1E,  # ORIYA LETTER NYA
    0x0B1F,  # ORIYA LETTER TTA
    0x0B20,  # ORIYA LETTER TTHA
    0x0B21,  # ORIYA LETTER DDA
    0x0B22,  # ORIYA LETTER DDHA
    0x0B23,  # ORIYA LETTER NNA
    0x0B24,  # ORIYA LETTER TA
    0x0B25,  # ORIYA LETTER THA
    0x0B26,  # ORIYA LETTER DA
    0x0B27,  # ORIYA LETTER DHA
    0x0B28,  # ORIYA LETTER NA
    0x0B2A,  # ORIYA LETTER PA
    0x0B2B,  # ORIYA LETTER PHA
    0x0B2C,  # ORIYA LETTER BA
    0x0B2D,  # ORIYA LETTER BHA
    0x0B2E,  # ORIYA LETTER MA
    0x0B2F,  # ORIYA LETTER YA
    0x0B30,  # ORIYA LETTER RA
    0x0B32,  # ORIYA LETTER LA
    0x0B33,  # ORIYA LETTER LLA
    0x0B35,  # ORIYA LETTER VA
    0x0B36,  # ORIYA LETTER SHA
    0x0B37,  # ORIYA LETTER SSA
    0x0B38,  # ORIYA LETTER SA
    0x0B39,  # ORIYA LETTER HA
    0x0B5C,  # ORIYA LETTER RRA
    0x0B5D,  # ORIYA LETTER RHA
    0x0B5F,  # ORIYA LETTER YYA
    0x0B71,  # ORIYA LETTER WA
    ]

Nukta = [
    0x0B3C,  # ORIYA SIGN NUKTA
    ]

Virama = [
    0x0B4D,  # ORIYA SIGN VIRAMA
    ]

Digits = [
    0x0B66,  # ORIYA DIGIT ZERO
    0x0B67,  # ORIYA DIGIT ONE
    0x0B68,  # ORIYA DIGIT TWO
    0x0B69,  # ORIYA DIGIT THREE
    0x0B6A,  # ORIYA DIGIT FOUR
    0x0B6B,  # ORIYA DIGIT FIVE
    0x0B6C,  # ORIYA DIGIT SIX
    0x0B6D,  # ORIYA DIGIT SEVEN
    0x0B6E,  # ORIYA DIGIT EIGHT
    0x0B6F,  # ORIYA DIGIT NINE
    ]

vowels = list(map(chr, Vowels))
matras = list(map(chr, Matras))
consonants = list(map(chr, Consonants))
n = nukta = list(map(chr, Nukta))[0]
h = virama = list(map(chr, Virama))[0]
digits = list(map(chr, Digits))
